---
cloudwatch_agent_log_group: /cops/app
cloudwatch_agent_log_dir: /var/log/copsapp
cloudwatch_agent_config_path: /opt/aws/amazon-cloudwatch-agent/etc/config.json
cloudwatch_agent_ctl: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
